export {default as Login} from './Login/Login';
export {default as MainScreen} from './MainScreen/MainScreen';
export {default as LoginthroughPhoneNo} from './Loginthrougphoneno/Loginthroughphoneno';
export {default as Otpscreen} from './../Screens/Otpscreen/Otpscreen';
export {default as LoginThroughEmail} from './LoginThroughEmail/LoginThroughEmail'
export {default as Home} from './Home/Home';
export {default as Chat} from './Chat/Chat';
export {default as Sell} from './Sell/Sell';
export {default as Acount} from './Account/Account';
export {default as Myads} from './MyAds/Myads';
export {default as SearchItem} from './Searchitem/Searchitem';
export {default as Locations} from './Locations/Locations';
export {default as CreateLoginEmail} from './CreateLoginEmail/CreateLoginEmail';
