export default {
  olxLog: require('./../assets/image/olxLog.png'),
  iphone: require('./../assets/image/iphone.png'),
  appleIcn: require('./../assets/image/ic_apple.png'),
  mark: require('./../assets/image/mark.png'),
  google: require('./../assets/image/google.png'),
  close: require('./../assets/image/close.png'),
  back: require('./../assets/image/back.png'),
  edit: require('./../assets/image/edit.png'),
  girl: require('./../assets/image/girl.png'),
  home: require('./../assets/image/ic_home.png'),
  chat: require('./../assets/image/chat.png'),
  user: require('./../assets/image/ic_user.png'),
  inactive: require('./../assets/image/inActiveHeart.png'),
  stories: require('./../assets/image/stories.png'),
  ic_grey_tick: require('./../assets/image/ic_grey_tick.png'),
  search: require('./../assets/image/ic_srch.png'),
  down: require('./../assets/image/ic_down.png'),
  ic_notify: require('./../assets/image/ic_notify.png'),
  work: require('./../assets/image/work.png'),
  pets: require('./../assets/image/pets.png'),
  two: require('./../assets/image/two.png'),
  phone: require('./../assets/image/phone.png'),
  car: require('./../assets/image/car.png'),
  computer: require('./../assets/image/computer.png'),
  real: require('./../assets/image/real.png'),
  audi: require('./../assets/image/audi.png'),
  ccar: require('./../assets/image/c.png'),
  blackHeart: require('./../assets/image/blackHeart.png'),
  whiteHeart: require('./../assets/image/whiteHeart.png'),
  share: require('./../assets/image/share.png'),
  car1: require('./../assets/image/car1.png'),
  car2: require('./../assets/image/car2.png'),
  car3: require('./../assets/image/car3.png'),
  car4: require('./../assets/image/car4.png'),
  car5: require('./../assets/image/car5.png'),
  car6: require('./../assets/image/car6.png'),
  gear:require('./../assets/image/gear.png'),
  fuel:require('./../assets/image/fuel.png'),
  meter:require('./../assets/image/meter.png'),
  chat1: require('./../assets/image/chat1.png'),
  phoneCalling: require('./../assets/image/phoneCalling.png'),
  check:require('./../assets/image/check.png'),

};
