export default {
    ACCOUNT: 'Acount',
    CHAT: 'Chat',
    LOGINTHROUGHEMAIL : 'LoginThroughEmail',
    HOME: 'Home',
    MAINSCREEN: 'MainScreen',
    OTPSCREEN: 'OtpScreen',
    LOGINTHROUGPHONENO: 'Loginthrougphoneno',
    SELL: 'SELL,',
    TABROUTES:'TabRoutes',
    MYADS:'MyAds',
    LOCATIONS:'Locations',
    SEARCHITEM:'SearchItem',
    CREATELOGINEMAIL:'CreateLoginEmail',
    SETTING :'Setting',
    BUYCAR:'Buycar',
    SELLCAR:'Sellcar',
    HOMESTACK:'HomeStack',
    SEEALL:'Seeall',
    OLXAUTOS:'Olxautos',
    PROPERTIES:'Properties',
    MOBILE:'Mobile',
    JOBS:'Jobs',
    BIKES:'Bikes',
    DETAILS:'Details',
  };
  